// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snwoerqlngclcfdokhwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNud29lcnFsbmdjbGNmZG9raHdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MDgxNDksImV4cCI6MjA3MDQ4NDE0OX0.-h4AZ7OutFEc5UUIgHBnFDCyUJa2C-32YhIInX3CvFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});